version: '3'
services: 
  slikk-authms-api: 
#     build: 
#       context: ./app
    container_name: slikk-authms-api
    image: 073645649421.dkr.ecr.eu-central-1.amazonaws.com/slikk-authms-api
    ports: 
      - "5001:5001"
  slikk-podms-api: 
#     build: 
#       context: ./app1
    container_name: slikk-podms-api
    image: 073645649421.dkr.ecr.eu-central-1.amazonaws.com/slikk-podms-api
    ports: 
      - "3000:3000"
  slikk-nginx-api: 
    container_name: slikk-nginx-api
    depends_on: 
      - slikk-podms-api
      - slikk-authms-api
    image: 073645649421.dkr.ecr.eu-central-1.amazonaws.com/slikk-nginx-api
    ports: 
      - "80:80"
#     build:
#       context: ./nginx
